kubernetes-sigs/etcdadm

constants/constants.go

etcdctl.sh: Source etcdctl.env using sh syntax

---

binary/etcd.go

binary: Create install dir

---

apis/config.go
binary/etcd.go
cmd/download.go
cmd/info.go
cmd/init.go
cmd/join.go
cmd/reset.go
cmd/root.go
cmd/version.go
constants/constants.go
etcd/etcd.go
main.go
preflight/mandatory.go
service/diff.go
service/etcdctl.go
service/systemd.go
service/unit.go
util/cmd.go
util/filesystem.go

As per https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories

Transfer copyright to "The etcdadm authors"

---

Makefile
README.md
apis/config.go
binary/etcd.go
certs/certs.go
certs/pkiutil/pki_helpers.go
certs/pkiutil/pki_helpers_test.go
cmd/download.go
cmd/info.go
cmd/init.go
cmd/join.go
cmd/reset.go
cmd/root.go
cmd/version.go
etcd/etcd.go
main.go
preflight/mandatory.go
service/diff.go
service/etcdctl.go
service/unit.go
version.sh

Fix import paths

---

cmd/init.go
cmd/join.go

etcdadm printing err which nil  instead of etcdAdmConfig.ReleaseURL, this PR fix that.

cmd: print artifact download url

---

README.md

etcdadm is awesome, and this PR help people better knowing what and where to copy the cert and key.

README: add command example of copying ca cert and key

---

docs/USECASES.md

/cc @justinsb @moshloop @neolit123

Add use cases doc

---

docs/USECASES.md

For some reason, #110 merged without this being caught.

Add missing newline to end of USECASES.md

---

binary/etcd.go

Simple check to download the etcd archive only if it does not exist alredy - fixes issue #73

only download etcd archive if it does not exist

---

cmd/join.go

Associate 'disk-priorities' flag to join command

---

Makefile
hack/verify-all.sh
hack/verify-version.sh
version.sh

Build etcdadm with correct version

---

test/e2e/init.sh
test/e2e/utils.sh

First step in addressing #107. I will follow this up with a prow presubmit job.
Signed-off-by: Daniel Lipovetsky <dlipovetsky@d2iq.com>
/cc @neolit123 @justinsb

test/e2e: init test

---

test/e2e/init.sh

Signed-off-by: Daniel Lipovetsky <dlipovetsky@d2iq.com>

test/e2e: Run etcdadm in docker

---

README.md
ROADMAP.md

Add project roadmap

---

.gitignore
binary/etcd.go

Signed-off-by: Chuck Ha <chuckh@vmware.com>

Minor clean up when running a command

---

hack/verify-golint.sh
hack/verify-govet.sh
hack/verify-whitespace.sh

We can then merge the repos and fix the problems here.

Exclude etcd-manager from the style checks for the moment

---

.github/workflows/main.yml

We moved from travis to github actions as it seems more reliable.

Add github actions tests from etcd-manager

---

dev/staging/push.sh
etcd-manager/dev/build-assets.sh

Part of moving canonical location of etcd-manager to this repo.

Build & stage etcd-manager also

---

etcd-manager/dev/build-assets.sh

With luck, this will be the last one!

Update with latest etcd-manager changes

---

dev/staging/push.sh

Fix staging build

---

etcd-manager/pkg/etcd/etcdprocess.go

https://github.com/etcd-io/etcd/blob/master/CHANGELOG-3.4.md#etcd-server-10
/cc @olemarkus

Set etcd server logger to "zap"

---

etcd-manager/images/base/BUILD

xRef: https://github.com/kubernetes/kops/issues/11323
/cc @olemarkus

Add "udev" to the etcd-manager image

---

etcd-manager/pkg/volumes/mounter.go

As kOps allows expanding etcd volumes, etcd-manager should also do this when started.
/cc @olemarkus

Perform file system resize on startup

---

etcd-manager/cmd/etcd-manager/main.go
etcd-manager/pkg/controller/controller.go
etcd-manager/pkg/etcd/etcdprocess.go
etcd-manager/pkg/etcd/etcdserver.go
etcd-manager/pkg/etcd/pki.go
etcd-manager/pkg/etcd/restore.go
etcd-manager/pkg/pki/BUILD.bazel
etcd-manager/pkg/pki/cas.go
etcd-manager/pkg/pki/certs.go
etcd-manager/pkg/pki/certutils.go
etcd-manager/pkg/pki/fs.go
etcd-manager/pkg/pki/fs_test.go
etcd-manager/pkg/pki/store.go
etcd-manager/pkg/tlsconfig/options.go
etcd-manager/test/integration/harness/cluster.go
etcd-manager/test/integration/harness/node.go

In preparation for allowing multiple CAs in trust bundles.

Cleanup etcd-manager PKI code

---

etcd-manager/pkg/pki/BUILD.bazel

Update BUILD.bazel to include fs_test.go

---

binary/etcd.go

Support linux other arch

---

.github/workflows/main.yml
etcd-manager/WORKSPACE
etcd-manager/test/integration/backuprestore/BUILD.bazel
etcd-manager/test/integration/backuprestore/backuprestore_test.go
etcd-manager/test/integration/harness/cluster.go
etcd-manager/test/integration/harness/node.go

We create a simple test that we can backup and restore, and that a
(single) key-value pair persists.

Create test for backup and restore functionality

---

.github/workflows/main.yml
dev/staging/push-etcdmanager.sh
etcd-manager/dev/build-assets.sh

Ref: https://testgrid.k8s.io/sig-k8s-infra-gcb#etcdadm-postsubmit-push-to-staging

Fix release of built assets for etcd-manager

---

hack/verify-all.sh

It's hard to see what failed sometimes, so print the failed scripts.

hack/verify-all: highlight failed tests

---

apis/config.go
constants/constants.go
service/env_test.go
service/testdata/buildenvironment/complex/in.yaml
service/testdata/buildenvironment/complex/want.txt

Working towards sharing the flag/env logic

Map additional flags as used by etcd-manager

---

etcd-manager/pkg/volumes/aws/volumes.go

Test for nil in to not found check

---

etcd-manager/docs/release-process.md

docs: update release process for new name of promotion tool

---

etcd-manager/WORKSPACE
etcd-manager/go.mod
etcd-manager/go.sum
etcd-manager/tools/deb-tools/WORKSPACE
etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/BUILD.bazel
etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/error.go
etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/hcloud.go
etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/labels.go
etcd-manager/vendor/github.com/hetznercloud/hcloud-go/hcloud/metadata/client.go
etcd-manager/vendor/modules.txt

Update hcloud-go to v1.33.2

---

etcd-manager/pkg/volumes/hetzner/discovery.go
etcd-manager/pkg/volumes/hetzner/volumes.go

Handle cases when GetById returns nil for Hetzner

---

etcd-manager/pkg/backupcontroller/cleanup.go

updated retention period from 7 years to 2 for daily backups

updated retention period from 7 years to 2 for daily backups

---

etcd-manager/docs/releases/3.0.md

/cc @justinsb @rifelpet @olemarkus

Release notes for etcd-manager 3.0.20220727

---

etcd-manager/Makefile

Sometimes it helps just being able to build the binaries.
/cc @olemarkus @rifelpet @justinsb

Add makefile targets for building etcd-manager

---

etcd-manager/pkg/volumes/hetzner/volumes.go

Wait for 1 minute for volume to be attached for Hetzner

---

etcd-manager/docs/release-process.md
etcd-manager/docs/releases/3.0.md

Release notes for etcd-manager 3.0.20220831

---

.github/workflows/main.yml
Makefile
dev/staging/cloudbuild.yaml
dev/staging/push-etcdmanager.sh
etcd-manager/cloudbuild-master.yaml
etcd-manager/cloudbuild.yaml

This should fix tests that run at PR merge time.

Use official Bazel container image with Cloud Build

---

etcd-manager/WORKSPACE

No known issues, just to satisfy scanners.

Update to latest distroless

---

etcd-manager/pkg/etcd/etcdserver.go
etcd-manager/test/integration/resize_cluster_test.go

Reverts kubernetes-sigs/etcdadm#361
/cc @justinsb 
/assign @justinsb

Revert "Restart the server using the recommended etcd version"

---

etcd-manager/docs/release-process.md

Update the etcd-manager release process

---

.github/workflows/main.yml
dev/staging/push-etcdmanager.sh

Just keeping up with versions.

chore: update bazelisk to 1.19.0
