kubernetes-sigs/etcdadm

- cmd/reset.go
fixing below SIGSEGV:
~/go/src/github.com/platform9/etcdadm>  ./etcdadm reset
INFO[0000] [reset] etcd service is running
INFO[0000] [membership] Checking if this member was removed
INFO[0000] [membership] Error checking membership: unable to create TLS client: open /etc/etcd/pki/etcdctl-etcd-client.key: permission denied
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbafec3]
goroutine 1 [running]:
github.com/platform9/etcdadm/cmd.glob..func5(0x1320980, 0x134cd00, 0x0, 0x0)
/home/nirmoy/go/src/github.com/platform9/etcdadm/cmd/reset.go:65 +0x863
github.com/platform9/etcdadm/vendor/github.com/spf13/cobra.(*Command).execute(0x1320980, 0x134cd00, 0x0, 0x0, 0x1320980, 0x134cd00) …
> reset: exit if failed to retrive client

- OWNERS_ALIASES
Typos happen when you approve your own PR :frowning_face: 
Thanks to @sarun87 for spotting the typos!
/assign @justinsb
> Fix group name typos and clean up OWNERS

- README.md
@haoqing0110 I realized too late that your example breaks if the target directory does not exist. The updated command creates the target directory if it does not exist.
> README.md: example of copying CA that works if target dir does not exist

- cmd/init.go
- cmd/join.go
- cmd/reset.go
- initsystem/initsystem.go
- initsystem/systemd.go
Implement issue https://github.com/kubernetes-sigs/etcdadm/issues/99.
Create new `initsystem` package similar to kubeadm https://github.com/kubernetes/kubernetes/tree/master/cmd/kubeadm/app/util/initsystem .
This is the first commit, i want to confirm if there is problem with this implementation, if no, i will continue.
Example code:
```go
initSystem, err := initsystem.GetInitSystem()
if err != nil {
log.Fatalf("[initsystem] Error detect the init system: %s", err)
}
active, err := initSystem.IsActive("etcd.service")
if err != nil {
log.Fatalf("[start] Error checking if etcd service is active: %s", err)
}
```
> Implement init system package to adapter different OS and mock tests

- binary/etcd.go
Add prefix `0`,  or it will be translated to decimal.
> bugfix: FileMode should be octal expressed

- hack/verify-spelling.sh
this was overlooked for go 1.12 and broke when we started using 1.13.
/kind bug
/priority important-soon
/assign @dlipovetsky
> fix the build of misspell for go 1.13

- cmd/init.go
- cmd/join.go
Fixes #75 
Verified certs generated by init and join have extra SANs:
```
etcdadm -l debug init --server-cert-extra-sans internal-etcd-2019121018425172030000000b-1499126190.us-west-2.elb.amazonaws.com --version 3.3.8
...
[certificates] Generated server certificate and key.
[certificates] server serving cert is signed for DNS names [internal-etcd-2019121018425172030000000b-1499126190.us-west-2.elb.amazonaws.com ip-10-0-1-23.us-west-2.compute.internal] and IPs [10.0.1.23 127.0.0.1]
```
```
etcdadm -l debug join --server-cert-extra-sans internal-etcd-2019121018425172030000000b-1499126190.us-west-2.elb.amazonaws.com --version 3.3.8 https://10.0.5.221:2379
...
[certificates] server serving cert is signed for DNS names [internal-etcd-2019121018425172030000000b-1499126190.us-west-2.elb.amazonaws. …
```
> Add a flag to support additional server SANs

- .gitignore
I update the lasted code, use `go mode vendor` that save the third party library to `vendor` directory, I found the `.gitignore` not ignore the `vendor` directory, so add this entry in `.gitignore` file.
> Ignore vendor directory when git push

- binary/etcd.go
Fixes: https://github.com/kubernetes-sigs/etcdadm/issues/144
Add `--fail` when using `curl` download etcd release package. 
If etcd release package not found, `etcdadm` will show below logs:
```diff
[root@k8s-1 ~]# etcdadm init --name k8s --release-url http://192.168.10.108/tools/etcd --version 3.3.12 -l debug
INFO[0000] [install] Artifact not found in cache. Trying to fetch from upstream: http://192.168.10.108/tools/etcd
INFO[0000] [install] Downloading & installing etcd http://192.168.10.108/tools/etcd from 3.3.12 to /var/cache/etcdadm/etcd/v3.3.12
INFO[0000] [install] downloading etcd from http://192.168.10.108/tools/etcd/v3.3.12/etcd-v3.3.12-linux-amd64.tar.gz to /var/cache/etcdadm/etcd/v3.3.12/etcd-v3.3.12-linux-amd64.tar.gz
+curl: (22) The requested URL returned error: 404 Not Found …
```
> Download etcd release abort and show error if package not found

- apis/config.go
- cmd/join.go
- constants/constants.go
Fixes: https://github.com/kubernetes-sigs/etcdadm/issues/133
Add exponential backoff retry for join etcd member at the same time, e.g. 0, 1, 2, 4, 8s. The max retry is five times.
> Add backoff retry when join member at the same time

- test/e2e/cluster.sh
Fixes: https://github.com/kubernetes-sigs/etcdadm/issues/149
Add `test/e2e/cluster.sh` to test join etcd member workflow, it use bash and docker to implement it.
I want to know wether this test case reasonable? If it ok, should i add pr to [kubernetes/test-infra](https://github.com/kubernetes/test-infra), like pr: https://github.com/kubernetes/test-infra/pull/14995 ?
> test/e2e: Join workflow test

- etcd/etcd.go
- go.mod
- go.sum
Fixes kubernetes-sigs/etcdadm#191 snapshot dependency changed to clientv3
In de following [commit](https://github.com/etcd-io/etcd/commit/143fbf4caaa5a2a314d4f79dc2285045f95ce04b#diff-a56f0d7147e0486b36275720b7df60eb) etcd moved files to clientv3 folder. So snapshot dependency should be this one.
Thanks for @neolit123 for pointing out the right path on [comment](https://github.com/kubernetes-sigs/etcdadm/issues/151#issuecomment-583640398)
Created a new cluster successfuly with a snapshot of a running kubernetes
> Etcd snapshot dep. failed do download because it moved folders

- Makefile
- README.md
There's an issue with `go get` (https://github.com/kubernetes-sigs/etcdadm/issues/156). For now, let's recommend building with `make`.
> Build with make

- cmd/init.go
- cmd/join.go
- cmd/reset.go
- initsystem/initsystem.go
- initsystem/systemd.go
By reducing the surface, we make it easier to implement other
backends (mock & kubelet)
> Pare down InitSystem interface

- hack/verify-gotest.sh
The go.mod means we'll have to run the tests from that subdirectory
(or converge the set of go.mod dependencies).
> Temporarily skip etcd-manager gotest

- binary/etcd.go
etcdadm supports only etcd v3, so it is correct to always use the etcdctl v3 interface.
Fixes #173.
> Always use etcdctl v3 interface

- constants/constants.go
I propose setting the default etcd version to whatever is used in the latest Kubernetes release.
Once this merges, I plan to create a new etcdadm release.
> Set default etcd version to 3.4.9, the default for Kubernetes 1.19

- version.sh
Otherwise other tags confuse the version script.
Equivalent to https://github.com/kubernetes/kubernetes/pull/83497
> build tooling: Allow custom tags to exist

- .gcloudignore
- dev/staging/README.md
- dev/staging/cloudbuild.yaml
- dev/staging/push.sh
Published the etcdadm binary to the staging bucket.
We'll want to include the etcd-manager build and build for multi-arch
in later steps.
> Initial cloudbuild staging job

- hack/verify-shellcheck.sh
the origin shellcheck output:
You are downloading ShellCheck from an outdated URL!
Please update to the new URL:
https://github.com/koalaman/shellcheck/releases/download/v0.6.0/shellcheck-v0.6.0.linux.x86_64.tar.xz
For more information, see:
https://github.com/koalaman/shellcheck/issues/1871
PS: Sorry for breaking your build. The hosting costs were getting out of hand :(
Signed-off-by: Li Zhijian <lizhijian@cn.fujitsu.com>
> update shellcheck url

- etcd-manager/dev/add-symlink.sh
- etcd-manager/dev/build-assets.sh
- etcd-manager/dev/check-hashes.sh
- etcd-manager/dev/release.sh
Signed-off-by: Li Zhijian <lizhijian@cn.fujitsu.com>
> etcd-manager/dev: move script interpreter to the first line

- etcd-manager/tools/deb-tools/go.mod
- etcd-manager/tools/deb-tools/vendor/github.com/go-logr/logr/BUILD.bazel
- etcd-manager/tools/deb-tools/vendor/k8s.io/klog/v2/BUILD.bazel
This was missed during the move, caught by `make vendor` in the etcd-manager directory
> Fix go module path for etcd-manager/tools/deb-tools

- dev/staging/cloudbuild.yaml
- dev/staging/push.sh
A little inefficient, but means that we can control our bazel version
and not rely on the upstream image.
> Install bazel in staging build

- dev/staging/push.sh
A double slash is preserved in GCS, so make sure that we don't introduce it!
Also fix source location for etcd-manager binaries.
> staging artifact upload: avoid double slash

- etcd-manager/OWNERS
As the main user for etcd-manager is kOps, makes sense to copy the OWNERS file from there to allow kOps maintainers to review PRs.
This has to be limited to those that are members of the kubernetes-sigs org.
> Add OWNERS file from kOps to etcd-manager

- etcd-manager/images/base/BUILD
For this to actually work, `/run` needs to be mounted inside the pod on kOps side, otherwise it does nothing.
xRef: https://github.com/kubernetes/mount-utils/blob/19c6fae41ad49f3e4026f28b043f41343aa852fd/mount_linux.go#L145-L166
Before:
```
I0429 04:57:20.495826    9315 mount_linux.go:192] Detected OS without systemd
I0429 04:57:20.497333    9315 mounter.go:241] matched device "/dev/nvme2n1" and "/dev/nvme2n1" via '\x00'
I0429 04:57:20.497364    9315 mounter.go:94] mounted master volume "vol-02aa61026842d90dd" on /mnt/master-vol-02aa61026842d90dd
```
After:
```
I0429 06:42:24.481969   51116 mount_linux.go:206] Detected OS with systemd
I0429 06:42:24.485360   51116 mounter.go:241] matched device "/dev/nvme2n1" and "/dev/nvme2n1" via '\x00'
I0429 06:42:24.485393   51116 mounter.go:94] …
```
> Add packages required for systemd mounts

- Makefile
Version 1.12 is no longer supported.
> Makefile: Update go version from 1.12 to 1.16

- OWNERS_ALIASES
This should support better integration between etcdadm / etcd-manager.
> OWNERS: Add etcd-manager owners to top-level owners

- dev/staging/push.sh
As it is a directory, we must pass the -r flag.
> staging build: copy dist directory recursively

- constants/constants.go
> Set default etcd version to 3.4.13, current for Kubernetes 1.19, 1.20, and 1.21

- constants/constants.go
- etcd-manager/WORKSPACE
- etcd-manager/images/BUILD
- etcd-manager/images/etcd.bzl
- etcd-manager/pkg/etcdversions/mappings.go
- etcd-manager/test/integration/BUILD.bazel
- etcd-manager/test/integration/clusterformation_test.go
- etcd-manager/test/integration/datapersists_test.go
- etcd-manager/test/integration/harness/cluster.go
k/k is planning to upgrade etcd to v3.5.0 for the v1.22 Kubernetes release.
xRef: https://github.com/kubernetes/kubernetes/issues/102294
> Add support for etcd 3.5.0

- apis/config.go
- cmd/init.go
- cmd/join.go
- cmd/reset.go
- constants/constants.go
- go.mod
- initsystem/initsystem.go
- initsystem/kubelet/initsystem.go
- initsystem/systemd.go
- service/unit.go
Building on top of #165:
* Move systemd exclusive code out of init and join commands
* Add a couple of flags to configure the init system type (kubelet or systemd) and the image repository
> Kubelet support improvements

- apis/config.go
- cmd/init.go
- cmd/join.go
this pull request adds `--bind-address` to specify listen address generated in `etcd.env`
> add custom bind addresss support to init

- etcd-manager/pkg/etcdversions/mappings.go
- etcd-manager/test/integration/upgradedowngrade/upgradedowngrade_test.go
Will make the upgrade/downgrade test faster, as discussed during kOps office hours.
> Use latest etcd versions for the upgrade/downgrade test

- etcd-manager/cmd/etcd-dump/main.go
- etcd-manager/pkg/controller/etcdclusterstate.go
- etcd-manager/pkg/etcd/restore.go
- etcd-manager/pkg/etcdclient/client.go
- etcd-manager/test/integration/harness/etcd.go
We need to explicitly specify a timeout on get operations, so that we
can detect if etcd exits.
> Detect if etcd exits during dump/restore operations

- etcd-manager/.gitignore
- etcd-manager/Makefile
- etcd-manager/tools/deb-tools/.bazelrc
- etcd-manager/tools/deb-tools/.gitignore
- etcd-manager/tools/deb-tools/Makefile
.bazel symlinks keep gopls (used by VSCode etc) happy.
> Use bazelisk and .bazel symlinks

- etcd-manager/pkg/etcdversions/mappings.go
This is a bit more future-proof and lower maintenance. This should cover all 3.X upgrades of up to one minor version.
ref: https://github.com/kubernetes/kops/issues/12662
> etcd-manager - Allow all 3.X upgrades of one minor version

- etcd-manager/pkg/etcd/etcdprocess.go
- etcd-manager/pkg/etcd/pki.go
- etcd-manager/pkg/etcd/restore.go
When restoring a backup for both etcd and etcd-events, I observed a
port-conflict on port 8002/8003.  Switching to unixs:// endpoints (unix
domain sockets) is a little more secure, and avoids the port conflict.
Due to https://github.com/etcd-io/etcd/issues/12450 the syntax is
slightly awkward - we have to make it look like a host and port.
> Use unixs for "restore source" endpoint

- dev/staging/push.sh
We were only using it for bazel invocations, but as we adopt more
bazelisk we would like to be able to invoke bazelisk explictly.
> Install bazelisk for bazel and bazelisk

- dev/staging/cloudbuild.yaml
- dev/staging/push-etcdadm.sh
- dev/staging/push-etcdmanager.sh
Because the versioning schemes are different (for now), and we want to
avoid rebuilds/reuploads to the same location.
> Split staging builds for etcdadm and etcd-manager

- dev/staging/cloudbuild.yaml
The version that is passed to us includes a date prefix, so we need to
compute our own tag.
Do this (initially) for etcd-manager only.
> staging builds: compute our own version

- etcd-manager/.gitignore
We have to specify the wildcard blob to get git to process this
correctly.
> Fix .gitignore to not ignore vendoring

- etcd-manager/cmd/etcd-manager/main.go
- etcd-manager/pkg/controller/controller.go
- etcd-manager/pkg/controller/newcluster.go
- etcd-manager/pkg/etcd/etcdprocess.go
- etcd-manager/pkg/etcd/etcdserver.go
- etcd-manager/pkg/etcd/pki.go
- etcd-manager/pkg/privateapi/peers.go
- etcd-manager/pkg/volumes/aws/discovery.go
- etcd-manager/pkg/volumes/aws/volumes.go
If instances are using Resource Based Naming, we are guaranteed to have ipv6 addresses and we use them between etcd-manager instances.
This will also make etcd-manager work in ipv6-native/only subnets.
This PR also makes it possible for etcd-manager to create an etcd cluster listening on ipv6, but the default remains listening on ipv4.
This PR is tested in https://github.com/kubernetes/kops/pull/12855
> Add support for listening to IPv6

- dev/staging/cloudbuild.yaml
We are now seeing timeouts with the 10 minute default; raise to 30
minutes.  We aren't running the tests, so 30 minutes should be plenty.
> staging build: increase timeout to 30 minutes

- etcd-manager/tools/deb-tools/.bazelversion
Otherwise we don't lock in the bazel version.
> Add bazelversion file to tools/deb-tools

- constants/constants.go
- service/testdata/buildenvironment/complex/want.txt
- service/testdata/buildenvironment/simple/want.txt
A zero value doesn't do anything anyway, and this helps strict
convergence with etcdadm & etcd-manager (it is one of the few flag
differences).
> Only emit GOMAXPROCS if non-zero

- etcd-manager/pkg/etcd/etcdprocess.go
This is likely safer, but also synchronizes with etcdadm configuration.
> Set ETCD_STRICT_RECONFIG_CHECK

- service/diff.go
Otherwise we get a spurious empty key/value pair in the map.
> environment: ignore empty lines when converting to map

- etcd-manager/test/integration/harness/node.go
We were stopping etcd first, then stopping the state machine which can
relaunch etcd.  Thus there was a risk that the state machine would
relaunch etcd.  This sometimes manifested itself as a failure to
cleanup test directories.
> testing: fix race stopping state machine vs stopping etcd

- .github/workflows/e2e.yml
- Makefile
- apis/config.go
- cmd/init.go
- cmd/join.go
- cmd/phases.go
- test/e2e/cluster_phases.sh
This adds the ability to run the init and join command in phases, very much inspired by `kubeadm`. This is very useful when having non conventional setups, where extra operations need to be done at some point during the workflow (for example, when using bottlerocket).
The implementation is very simple, it doesn't allow for most of the fancy stuff the `kubeadm` one does.
This can only run one phase at a time.
It makes the assumption that all phases are idempotent.
Phases can be run as sub-commands for the init and join commands:
```sh
etcdadm init phase --help
Use this command to invoke single phase of the init command
Usage:
etcdadm init phase [command]
Available Commands:
certificates           Run certificates phase
configure              Run configure phase
etcdctl                Run …
```
> Init and join command phases

- etcd-manager/pkg/volumes/aws/discovery.go
- etcd-manager/pkg/volumes/aws/volumes.go
etcd-manager assumed RBN implied IPv6, but that is not the case. Now it will actually check for an ipv6 address.
Kops-related note: This bug does not affect kops 1.22, which does not use RBN at all. But it will affect 1.23+.
> Fix ipv6 detection

- Makefile
- README.md
Related issue: #295 
1. Modify makefile to support GOPROXY on `container-build` command
2. Add `GOPROXY` use case in README
> `make container-build` support GOPROXY env

- apis/config.go
- cmd/init.go
- cmd/join.go
- constants/constants.go
- initsystem/kubelet/initsystem.go
Makes etcd data directory and kubelet podspec directory configurable through flags for `init` and `join` commands.
Both are optional and default to the same values as we currently use.
> Flags for etcd data dir and kubelet podspec dir

- etcd-manager/pkg/etcd/BUILD.bazel
- etcd-manager/pkg/etcd/etcdprocess.go
This is the recomended mitigation for the 3.5 series, and is planned
to be the default in 3.6
> Set ETCD_EXPERIMENTAL_INITIAL_CORRUPT_CHECK for etcd 3.5.x

- etcd-manager/test/integration/backuprestore/backuprestore_test.go
This makes the test similar to what `etcd-manager` does during the restore operation:
https://github.com/kubernetes-sigs/etcdadm/blob/f9a20374ca1abc9a6083e6db21aeaa32e2560504/etcd-manager/pkg/etcd/restore.go#L125-L133
```
cluster.go:67] Starting new testharness for "TestBackupRestore/backupEtcdVersion=3.5.0/restoreEtcdVersion=3.5.4" in /tmp/1003361396
backuprestore_test.go:51] Starting backup node 127.0.0.1 with etcd version "3.5.0"
backuprestore_test.go:59] Writing key "/testing/backuprestore_3.5.0"="world-3.5.0" to backup node
backuprestore_test.go:65] Reading key "/testing/backuprestore_3.5.0" from backup node
backuprestore_test.go:74] Found key "/testing/backuprestore_3.5.0" with value "world-3.5.0" in backup
backuprestore_test.go:77] Waiting for backup
backuprestore_test.go:81] …
```
> Use EtcdVersionForRestore in backuprestore test

- etcd-manager/pkg/volumes/hetzner/volumes.go
If `volume.LocalDevice` is set etcd-manager will consider that the volume is mounted to the current server:
https://github.com/kubernetes-sigs/etcdadm/blob/7b9d5aafe83d5f94e37f00111b29b61d1800004c/etcd-manager/pkg/volumes/mounter.go#L299-L302
> Fix reattachment of volumes for Hetzner

- etcd-manager/pkg/volumes/openstack/BUILD.bazel
- etcd-manager/pkg/volumes/openstack/testdata/metadata_drive.json
- etcd-manager/pkg/volumes/openstack/testdata/metadata_service.json
- etcd-manager/pkg/volumes/openstack/volumes.go
- etcd-manager/pkg/volumes/openstack/volumes_test.go
- etcd-manager/vendor/k8s.io/utils/exec/testing/BUILD.bazel
- etcd-manager/vendor/k8s.io/utils/exec/testing/fake_exec.go
- etcd-manager/vendor/modules.txt
This adds the config drive as an additional source for instance metadata when using OpenStack.
The reasoning behind this is that the Metadata Service may not always be reachable. For example when not using DHCP on a tenant network, or using a provider network (and at least according to our OpenStack support, the config drive is far more stable to use than the Metadata Service).
Currently, the search order is hard coded to `configDrive, metadataService`. So the code tries to look up the metadata in the config drive first and if not successful it will query the Metadata Service Endpoint. I did it this way because I think/assume the config drive lookup will fail faster in case it is not available.
Basically, the code is lifted/borrowed and adapted from the external OpenStack provider:
* …
> Add config drive as a source for OpenStack instance metadata

- etcd-manager/pkg/volumes/hetzner/discovery.go
- etcd-manager/pkg/volumes/hetzner/volumes.go
Goes together with https://github.com/kubernetes/kops/pull/14181.
```sh
$ hcloud volume list -o columns=name,server -s name 
NAME                                       SERVER
etcd-1.etcd-events.test1.k8s.local         master-fsn1-1-572f678e19233740
etcd-1.etcd-main.test1.k8s.local           master-fsn1-1-572f678e19233740
etcd-2.etcd-events.test1.k8s.local         master-fsn1-2-35d166ac6dc945b1
etcd-2.etcd-main.test1.k8s.local           master-fsn1-2-35d166ac6dc945b1
etcd-3.etcd-events.test1.k8s.local         master-fsn1-3-7af95061338a68fd
etcd-3.etcd-main.test1.k8s.local           master-fsn1-3-7af95061338a68fd
```
/hold for feedback
/cc @justinsb @olemarkus
> Use volume name tag to match the instance group for Hetzner

- etcd-manager/images/BUILD
- etcd-manager/pkg/etcd/etcdprocess.go
Having bin dirs like `"/opt/etcd-"+etcdVersion+"-"+runtime.GOOS+"-"+runtime.GOARCH` doesn't add any extra value these days, considering we have multi-arch images. It actually makes features like https://github.com/kubernetes/kops/pull/14785 harder to implement.
> Trim the os and arch suffix from bin dir name

- etcd-manager/Makefile
- etcd-manager/cloudbuild-master.yaml
- etcd-manager/cloudbuild.yaml
- etcd-manager/images/BUILD
The suffix could be either `slim`, `lite`, or something else entirely.
/cc @justinsb
> Build slim etcd-manager image without etcd binaries

- cmd/info.go
- cmd/init.go
- cmd/join.go
- cmd/reset.go
- etcd/etcd.go
We should be closing these when we are done with the connection,
otherwise we leak goroutines.
> etcdadm: Should close GRPC clients

- etcd-manager/pkg/etcd/etcdserver.go
- etcd-manager/test/integration/resize_cluster_test.go
When we load a version from disk, we run the latest recommended patch
version.  This enables us to depend on fewer versions of etcd.
Co-authored-by: Justin SB
> Restart the server using the recommended etcd version

- dev/staging/cloudbuild.yaml
- dev/staging/push-etcdadm.sh
Follow-up to #366.
```
Step #0: go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
Step #0: + gsutil -h 'Cache-Control:private, max-age=0, no-transform' -m cp -n etcdadm gs://k8s-staging-etcdadm/ci/builds/v20230206-etcd-managerv3.0.20230201-26-ge6741679/etcdadm
Step #0: dev/staging/push-etcdadm.sh: line 39: gsutil: command not found
Finished Step #0
ERROR
ERROR: build step 0 "golang:1.19" failed: step exited with non-zero status: 127
```
> Add gsutil when using Cloud Build

- etcd-manager/cmd/etcd-manager/BUILD.bazel
- etcd-manager/cmd/etcd-manager/main.go
- etcd-manager/cmd/etcd-manager/main_test.go
- etcd-manager/pkg/volumes/openstack/BUILD.bazel
- etcd-manager/pkg/volumes/openstack/discovery.go
- etcd-manager/pkg/volumes/openstack/util.go
- etcd-manager/pkg/volumes/openstack/util_test.go
- etcd-manager/pkg/volumes/openstack/volumes.go
Currently, `etcd-manager` returns the first found fixed IP address on VMs with multiple IP addresses in OpenStack.
However, there are multiple implications, for example:
* The first found IP address might not be the right one
* The first found IP address can vary everytime `etcd-manager` is executed due to inconsistent sorting of the results returned by the OpenStack compute API
* ETCD members can choose IP addresses located in different subnets which can lead to a non-functioning cluster 
To mitigate this, let users specify a filter with CIDR notation so that instead of the first found fixed IP address the first IP address matching the CIDR notation will be returned.
When no filter is specified `etcd-manager` will still return the first found fixed IP address.
> OpenStack: Filter fixed IP addresses with CIDR notation

- etcd-manager/cloudbuild-master.yaml
- etcd-manager/cloudbuild.yaml
Reference https://github.com/kubernetes/k8s.io/issues/5059
This changes machine type from N1 to E2 which are newer but almost same pricing. But with E2 being more efficient and overall taking less time. The cost can be reduced.
> Switched from N1 to E2 machine

- etcd-manager/WORKSPACE
No known issues, just to keep scanners from complaining.
> Update to golang 1.19.9

- etcd-manager/tools/deb-tools/main.go
This will be needed for bullseye.
Also clean up an empty if statement.
> debtools: use bigger buffer

- etcd-manager/pkg/volumes/scaleway/BUILD.bazel
- etcd-manager/pkg/volumes/scaleway/discovery.go
- etcd-manager/pkg/volumes/scaleway/volumes.go
- etcd-manager/vendor/github.com/scaleway/scaleway-sdk-go/api/ipam/v1alpha1/BUILD.bazel
- etcd-manager/vendor/github.com/scaleway/scaleway-sdk-go/api/ipam/v1alpha1/ipam_sdk.go
- etcd-manager/vendor/modules.txt
Since the release of IPAM at Scaleway, some services (like load-balancers) no longer work with the IP provided by the instance API.
This PR makes the etcd-manager use the IPs from IPAM instead.
> scaleway: get IPs from IPAM instead of instance API

- README.md
> Specify that using GOPROXY is not necessary for all users and remove implied endorsement of goproxy.io

- etcd-manager/pkg/volumes/openstack/util.go
This avoids a test flake, and makes production more predictable also.
> openstack: try to consistently return addresses from the first network
